name: Build on Tag

on:
  push:
    tags:
      - 'v*' # Triggers on any tag starting with 'v'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish --configuration Release --no-build /p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml
      
    - name: List Directory Content
      run: Get-ChildItem -Path "." -Recurse
      
    - name: Zip Release
      run: Compress-Archive -Path ".\bin\Release\net8.0-windows\publish\*" -DestinationPath GoombaCast.zip
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: GoombaCast.zip
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
